<?php
require('../includes/common.php');
if (!$_SESSION['set']) {
    header('location:../index.php');
}
$msg =' ';
if (isset($_POST['submit'])) {
    $fname = $_POST['fname'];
    $lname = $_POST['lname'];
    $desig = $_POST['desig'];
    $phone = $_POST['phone'];
    $mailid = $_POST['mailid'];
    $dept = $_POST['Department'];
    $locationstatus = $_POST['locationstatus'];
    $query = "INSERT INTO employee(fname,lname,designation,lid)VALUES('" . $fname . "','" . $lname . "','" . $desig . "','".$dept."')";
    $sql = mysqli_query($con, $query) or die(mysqli_error($con));
    $instid = mysqli_insert_id($con); //returns the ID generated by a query on a table with a column having the AUTO_INCREMENT attribute or the value for the last usage of LAST_INSERT_ID(expr).
    //echo $instid;
    $query3 = "INSERT INTO callerid(locationstatus,phone,eid) VALUES('" . $locationstatus . "','" . $phone . "','" . $instid . "')";
    //echo $query3;
    $result2 = mysqli_query($con, $query3) or die(mysqli_errno($con));
    $query4 = "INSERT INTO emailid(mailid,eid) VALUES('" . $mailid . "','" . $instid . "')";
    $result3 = mysqli_query($con, $query4) or die(mysqli_errno($con));
    $msg = "Added successfully.";
}
?>
<!DOCTYPE html>

<head>
    <title>Admin| Add Users</title>
     <link type="text/css" href="include/bootstrap.min.css" rel="stylesheet">
    <link type="text/css" href="include/bootstrap-responsive.min.css" rel="stylesheet">

    <link type="text/css" href="include/theme.css" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/css/bootstrap-responsive.min.css">
   
</head>

<body>
    <div class="wrapper">
        <div class="container">
            <div class="row">
                <?php include('include/sidebar.php'); ?>
                <div class="span9">
                    <div class="content">

                        <div class="module">
                            <div class="module-body">

                                <?php if ($msg) {
                                    printf(htmlentities($msg));
                                } ?>

                                <br />

                                <form class="form-horizontal row-fluid" method="post">

                                    <div class="control-group">
                                        <label class="control-label"><b>First Name</b> </label>
                                        <div class="controls">
                                            <input type="text" placeholder="Enter First Name" name="fname" class="span8 tip" required>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label"><b>Last Name</b> </label>
                                        <div class="controls">
                                            <input type="text" placeholder="Enter Last Name" name="lname" class="span8 tip" required>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label"><b>Department</b> </label>
                                        <div class="controls">
                                            <select name="Department" id="Department" class="span8 tip" required>
                                                <?php
                                                $queryLo = "SELECT lid FROM location";
                                                $resultLo = mysqli_query($con, $queryLo) or die(mysqli_errno($con));
                                                printf("<option selected disabled>Open this select menu</option>");
                                                while ($rowLo = mysqli_fetch_array($resultLo)) {
                                               
                                                printf("<option value=".$rowLo["lid"].">".$rowLo["lid"]."</option>");
                                                }
                                                ?>

                                            </select>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label"><b>Designation</b> </label>
                                        <div class="controls">
                                            <select name="desig" id="desig" class="span8 tip" required>
                                                <option selected disabled>Open this select menu</option>
                                                <option value="hod">HOD</option>
                                                <option value="professor">Professor</option>
                                                <option value="associate professor">Associate Professor</option>
                                                <option value="assistant professor">Assistant Professor</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="control-group">

                                        <label class="control-label"><b>Phone Number status</b> </label>
                                        <div class="controls">
                                            <input type="radio" name="locationstatus" value="office">Office
                                            <input type="radio" name="locationstatus" value="home">Home
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label"><b>Phone No</b> </label>
                                        <div class="controls">
                                            <input type="tel" placeholder="Enter Phone No" name="phone" class="span8 tip" maxlength="4" minlength="4" required>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label"><b>Official Email</b> </label>
                                        <div class="controls">
                                            <input type="email" placeholder="Enter Official Email" autocomplete="off" name="mailid" class="span8 tip" required>
                                        </div>
                                    </div>
                                    <button type="submit" name="submit" class="btn btn-success">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <!--/.content-->
                </div>
                <!--/.span9-->
            </div>
        </div>
        <!--/.container-->
    </div>
    <!--/.wrapper-->
</body>

</html>